### ISSUE TITLE
Reduce CI cost

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/infrastructure#140]
## Problem Statement

Zephyr CI uses the AWS "Spot" instances to save the computing cost. Spot instances are specially priced preemptible computing nodes allocated from the idling servers in the AWS, and may be up to 90% cheaper than the conventional on-demand instances.

Spot instance prices change based on their demand and they have increased significantly (almost by 100%) over the past few months; moreover, [the prices are unlikely to come down to the level they were before, as more companies are looking to cut costs and switch to using the spot instances](https://pauley.me/post/2023/spot-price-trends/).

For instance, the price for the `c5a.4xlarge` instances, the primary instance type used in the Zephyr CI, has increased from $0.156/hr to $0.323/hr, effectively doubling the CI cost for us.

## Possible Solutions

* **Multi-cloud provider architecture with self-hosted option**
    * Leveraging multiple cloud providers (backends) for cost optimisation
    * Running extremely cost optimised self-hosted cloud infrastructure as one of the backends
    * For more details, see https://github.com/zephyrproject-rtos/infrastructure/issues/150
* Reduce the amount of wasted computing resources in the CI
    * Improve CI workflow orchestration such that CI build workflows run only when the compliance check workflows succeed.
    * Consolidate the Zephyr tests to reduce the amount of duplicate builds.
* Switch to a different price model and/or provider
    * Switch to the reserved instances from the AWS, which are approximately 50% cheaper than the on-demand instances
    * Switch to a different cloud provider that offers better and more stable pricing.

**Comment by kartben** [comment]
> Improve CI workflow orchestration such that CI build workflows run only when the compliance check workflows succeed.

+1, this could probably make a big difference.
Although it may sound like defeating the original intent, I wonder if we should keep the current behavior for first-time contributors though? They're only a small portion of the PRs we get, *and* they will always tend to get "a bit of everything" wrong the first time around, so it might better to run all the workflows upfront anyway?

**Comment by stephanosio** [comment]
> I wonder if we should keep the current behavior for first-time contributors though? They're only a small portion of the PRs we get, _and_ they will always tend to get "a bit of everything" wrong the first time around, so it might better to run all the workflows upfront anyway?

I see no reason why it should be different for the first-time contributors. It does not make sense to build something that does not pass basic compliance checks, whether the PR is from a first-time contributor or an experienced contributor.

If any, throwing less errors at once, it will make the process less overwhelming for the first-time contributors.

**Comment by kartben** [comment]
Fair enough :)

**Comment by stephanosio** [comment]
Going to explore an alternate path using self-hosted OpenStack cluster with the Ampere Mt. Collins 2U server alongside other dirt cheap old servers because the AWS spot price has been ever rising and, only to make matters worse, so has the amount of our CI workloads.

Simply looking to reduce and optimise the amount of CI workloads would be unsustainable and would not be the best use of everyone's time.

**Comment by stephanosio** [comment]
"Multi-cloud provider architecture with self-hosted option" (aka. #150) has successfully reduced the overall CI operating cost to almost half (with potential for further reduction by optimising the AWS resource usage).
