### ISSUE TITLE
Open up Zephyr Security project to allow generic assignment of issues/tasks

### ISSUE THREAD

**Issue by dleach02** [zephyrproject-rtos/infrastructure#186]
I need to allow security group members to be able to assign tickets to the Security project area.

**Comment by stephanosio** [comment]
@zephyrproject-rtos/security has been added as a collaborator with write access to the [Security Project](https://github.com/orgs/zephyrproject-rtos/projects/34/).

**Comment by dleach02** [comment]
Thank you. Confirmed it is working as expected.
