### ISSUE TITLE
Requesting the setup of a Testing WG GitHub project area

### ISSUE THREAD

**Issue by dleach02** [zephyrproject-rtos/infrastructure#187]
I would like to establish a Testing WG project area to allow tracking of tickets and actions for this WG.

(@hakehuang)

**Comment by hakehuang** [comment]
Thanks David for this request. as to the details, what I am thinking is:

1. test results for boards, and connect to elasticsearch
2. test tools that can help to analysis test result
3. pilot test cases/framework for twister
4. documents/plans/proposal for test / CI

any comments? 
@nashif , @dleach02 , @PerMac, @golowanow

**Comment by PerMac** [comment]
@dleach02 are you thinking about sth like this https://github.com/orgs/zephyrproject-rtos/projects/14/views/1?

**Comment by hakehuang** [comment]
https://github.com/zephyrproject-rtos/infrastructure/issues/187 @dleach02  we have it now.

**Comment by dleach02** [comment]
> @dleach02 are you thinking about sth like this [github.com/orgs/zephyrproject-rtos/projects/14/views/1](https://github.com/orgs/zephyrproject-rtos/projects/14/views/1)?

We can use that but it seems very focused on test framework and twister. 

The RFC I want tracked by quality is #73043. So let me know if this is appropriate for the project area. I'll link it for now.

**Comment by hakehuang** [comment]
> The RFC I want tracked by quality is #73043. So let me know if this is appropriate for the project area. I'll link it for now.

hi David, please use this project https://github.com/orgs/zephyrproject-rtos/projects/48

**Comment by dleach02** [comment]
Okay. I've moved the RFC ticket outlining the gov board goals to the project area.
