### ISSUE TITLE
Create builds.zephyrproject.org S3 key for zephyr-lang-rust

### ISSUE THREAD

**Issue by d3zd3z** [zephyrproject-rtos/infrastructure#210]
The `zephyr-lang-rust` module needs a place to publish the generated documentation. It makes sense for it to be able to push  to `/zephyr-lang-rust/**`.

There will be two places to push `/zephyr-lang-rust/pr/12345/` will be used for each PR. This should have a lifecycle rule similar to the existing workflows in the `zephyr` repo.

The other will be to something like `zephyr-lang-rust/main/` to hold the docs generated for the current `main` branch on the repo. This should not be removed via rule, as there will only be one instance, which will be the latest version. This will be useful to people who wish to use the module ahead of the version mentioned in the main zephyr repo.

Documentation will also be included in the main Zephyr documentation, for the version of the module included in the module yaml file, but that is separate from this issue.

**Comment by d3zd3z** [comment]
Any status on this?

**Comment by stephanosio** [comment]
`vars.AWS_BUILDS_ZEPHYR_LANG_RUST_PR_ACCESS_KEY_ID` and `secrets.AWS_BUILDS_ZEPHYR_LANG_RUST_PR_SECRET_ACCESS_KEY` have been added to the `zephyr-lang-rust` repository and can now be accessed from the repository workflows.

This access key has write access to `arn:aws:s3:::builds.zephyrproject.org/zephyr-lang-rust/pr/*`.
